'use client';

import { useEffect, useState } from 'react';

type Memory = { id: string; text: string; createdAt: string };
const KEY = 'dosthai-memory';

export default function MemoryPage() {
  const [items, setItems] = useState<Memory[]>([]);
  const [text, setText] = useState('');
  useEffect(() => { try { setItems(JSON.parse(localStorage.getItem(KEY) || '[]')); } catch { setItems([]); } }, []);
  function save(next: Memory[]) { setItems(next); localStorage.setItem(KEY, JSON.stringify(next)); }
  function add() { const value = text.trim(); if (!value) return; save([{ id: crypto.randomUUID(), text: value, createdAt: new Date().toISOString() }, ...items]); setText(''); }
  return <main className="memory"><header><a href="/">← Dosthai</a><div><strong>Memory</strong><small>Review and control what Dosthai remembers.</small></div></header><section><div className="intro"><span>PERSONAL MEMORY</span><h1>Your memories</h1><p>Memory should be visible and controllable. These memories are stored locally in this version; cloud memory remains gated behind authenticated persistence and privacy controls.</p></div><div className="composer"><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="Add something you want Dosthai to remember…"/><button onClick={add} disabled={!text.trim()}>Save memory</button></div><div className="toolbar"><span>{items.length} saved {items.length === 1 ? 'memory' : 'memories'}</span><button onClick={() => save([])} disabled={!items.length}>Clear all</button></div>{items.map((item) => <article key={item.id}><div>✦</div><p>{item.text}</p><button onClick={() => save(items.filter((m) => m.id !== item.id))} aria-label="Delete memory">×</button></article>)}</section><style jsx>{`.memory{min-height:100vh;background:#090b10;color:#f4f5f7;font-family:Inter,system-ui,sans-serif}.memory header{height:64px;border-bottom:1px solid #20232d;display:flex;align-items:center;gap:24px;padding:0 24px;background:#0c0f15}.memory header a{color:#aeb5c3;text-decoration:none}.memory header div{display:flex;flex-direction:column}.memory header small{color:#737c8d;font-size:10px;margin-top:2px}.memory section{max-width:850px;margin:auto;padding:45px 20px 80px}.intro span{font-size:10px;letter-spacing:.14em;color:#747d8e;font-weight:800}.intro h1{font-size:38px;letter-spacing:-1.5px;margin:9px 0}.intro p{color:#8b94a4;line-height:1.7;font-size:13px}.composer{margin-top:25px;background:#11151d;border:1px solid #292f3a;border-radius:15px;padding:10px}.composer textarea{width:100%;box-sizing:border-box;min-height:90px;background:transparent;border:0;outline:0;color:white;padding:9px;resize:vertical}.composer button{border:0;border-radius:9px;background:#f0f1f3;color:#111;padding:9px 13px;font-size:11px;font-weight:700}.composer button:disabled{opacity:.4}.toolbar{display:flex;justify-content:space-between;color:#727b8c;font-size:10px;margin:20px 2px 8px}.toolbar button{border:0;background:transparent;color:#a3aab8;font-size:10px}article{display:flex;align-items:flex-start;gap:12px;background:#11151d;border:1px solid #292f3a;border-radius:12px;padding:14px;margin-top:7px}article>div{color:#8b7fff}article p{margin:0;flex:1;font-size:12px;line-height:1.6;color:#d8dce3}article button{border:0;background:transparent;color:#747d8c;font-size:18px}@media(max-width:600px){.memory section{padding:30px 14px}.intro h1{font-size:31px}}`}</style></main>;
}
